# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
spec:
  selector:
    app: flask-app
  type: LoadBalancer  
  ports:
  - name: flask-app
    port: 4000
    targetPort: 4000
  
