apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-league-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-league-app
  template:
    metadata:
      labels:
        app: devops-league-app
    spec:
      containers:
        - name: devops-league-app
          image: devops-league-app:latest  # Updated image name and tag
          ports:
            - containerPort: 4000  # Update to match the port your Flask app is running on
